/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DomainPoliyInitParameters struct {

	// (String) ID of the organization
	// ID of the organization
	// +crossplane:generate:reference:type=github.com/vhdirk/crossplane-provider-zitadel/apis/zitadel/v1alpha1.Organization
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("id", true)
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in zitadel to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in zitadel to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	// (Boolean)
	SMTPSenderAddressMatchesInstanceDomain *bool `json:"smtpSenderAddressMatchesInstanceDomain,omitempty" tf:"smtp_sender_address_matches_instance_domain,omitempty"`

	// (Boolean) User login must be domain
	// User login must be domain
	UserLoginMustBeDomain *bool `json:"userLoginMustBeDomain,omitempty" tf:"user_login_must_be_domain,omitempty"`

	// (Boolean) Validate organization domains
	// Validate organization domains
	ValidateOrgDomains *bool `json:"validateOrgDomains,omitempty" tf:"validate_org_domains,omitempty"`
}

type DomainPoliyObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the organization
	// ID of the organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (Boolean)
	SMTPSenderAddressMatchesInstanceDomain *bool `json:"smtpSenderAddressMatchesInstanceDomain,omitempty" tf:"smtp_sender_address_matches_instance_domain,omitempty"`

	// (Boolean) User login must be domain
	// User login must be domain
	UserLoginMustBeDomain *bool `json:"userLoginMustBeDomain,omitempty" tf:"user_login_must_be_domain,omitempty"`

	// (Boolean) Validate organization domains
	// Validate organization domains
	ValidateOrgDomains *bool `json:"validateOrgDomains,omitempty" tf:"validate_org_domains,omitempty"`
}

type DomainPoliyParameters struct {

	// (String) ID of the organization
	// ID of the organization
	// +crossplane:generate:reference:type=github.com/vhdirk/crossplane-provider-zitadel/apis/zitadel/v1alpha1.Organization
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in zitadel to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in zitadel to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	SMTPSenderAddressMatchesInstanceDomain *bool `json:"smtpSenderAddressMatchesInstanceDomain,omitempty" tf:"smtp_sender_address_matches_instance_domain,omitempty"`

	// (Boolean) User login must be domain
	// User login must be domain
	// +kubebuilder:validation:Optional
	UserLoginMustBeDomain *bool `json:"userLoginMustBeDomain,omitempty" tf:"user_login_must_be_domain,omitempty"`

	// (Boolean) Validate organization domains
	// Validate organization domains
	// +kubebuilder:validation:Optional
	ValidateOrgDomains *bool `json:"validateOrgDomains,omitempty" tf:"validate_org_domains,omitempty"`
}

// DomainPoliySpec defines the desired state of DomainPoliy
type DomainPoliySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DomainPoliyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DomainPoliyInitParameters `json:"initProvider,omitempty"`
}

// DomainPoliyStatus defines the observed state of DomainPoliy.
type DomainPoliyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DomainPoliyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DomainPoliy is the Schema for the DomainPoliys API. Resource representing the custom domain policy of an organization.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,zitadel}
type DomainPoliy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.smtpSenderAddressMatchesInstanceDomain) || (has(self.initProvider) && has(self.initProvider.smtpSenderAddressMatchesInstanceDomain))",message="spec.forProvider.smtpSenderAddressMatchesInstanceDomain is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userLoginMustBeDomain) || (has(self.initProvider) && has(self.initProvider.userLoginMustBeDomain))",message="spec.forProvider.userLoginMustBeDomain is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.validateOrgDomains) || (has(self.initProvider) && has(self.initProvider.validateOrgDomains))",message="spec.forProvider.validateOrgDomains is a required parameter"
	Spec   DomainPoliySpec   `json:"spec"`
	Status DomainPoliyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DomainPoliyList contains a list of DomainPoliys
type DomainPoliyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DomainPoliy `json:"items"`
}

// Repository type metadata.
var (
	DomainPoliy_Kind             = "DomainPoliy"
	DomainPoliy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DomainPoliy_Kind}.String()
	DomainPoliy_KindAPIVersion   = DomainPoliy_Kind + "." + CRDGroupVersion.String()
	DomainPoliy_GroupVersionKind = CRDGroupVersion.WithKind(DomainPoliy_Kind)
)

func init() {
	SchemeBuilder.Register(&DomainPoliy{}, &DomainPoliyList{})
}
