/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type InstanceMemberInitParameters struct {

	// (Set of String) List of roles granted, full list available here: https://zitadel.com/docs/guides/manage/console/managers#roles
	// List of roles granted, full list available here: https://zitadel.com/docs/guides/manage/console/managers#roles
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) ID of the user
	// ID of the user
	// +crossplane:generate:reference:type=github.com/vhdirk/crossplane-provider-zitadel/apis/zitadel/v1alpha1.HumanUser
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("id", true)
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a HumanUser in zitadel to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v1.Reference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a HumanUser in zitadel to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v1.Selector `json:"userIdSelector,omitempty" tf:"-"`
}

type InstanceMemberObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) List of roles granted, full list available here: https://zitadel.com/docs/guides/manage/console/managers#roles
	// List of roles granted, full list available here: https://zitadel.com/docs/guides/manage/console/managers#roles
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) ID of the user
	// ID of the user
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type InstanceMemberParameters struct {

	// (Set of String) List of roles granted, full list available here: https://zitadel.com/docs/guides/manage/console/managers#roles
	// List of roles granted, full list available here: https://zitadel.com/docs/guides/manage/console/managers#roles
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) ID of the user
	// ID of the user
	// +crossplane:generate:reference:type=github.com/vhdirk/crossplane-provider-zitadel/apis/zitadel/v1alpha1.HumanUser
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a HumanUser in zitadel to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v1.Reference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a HumanUser in zitadel to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v1.Selector `json:"userIdSelector,omitempty" tf:"-"`
}

// InstanceMemberSpec defines the desired state of InstanceMember
type InstanceMemberSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     InstanceMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceMemberInitParameters `json:"initProvider,omitempty"`
}

// InstanceMemberStatus defines the observed state of InstanceMember.
type InstanceMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InstanceMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InstanceMember is the Schema for the InstanceMembers API. Resource representing the membership of a user on an instance, defined with the given role.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,zitadel}
type InstanceMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roles) || (has(self.initProvider) && has(self.initProvider.roles))",message="spec.forProvider.roles is a required parameter"
	Spec   InstanceMemberSpec   `json:"spec"`
	Status InstanceMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceMemberList contains a list of InstanceMembers
type InstanceMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InstanceMember `json:"items"`
}

// Repository type metadata.
var (
	InstanceMember_Kind             = "InstanceMember"
	InstanceMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InstanceMember_Kind}.String()
	InstanceMember_KindAPIVersion   = InstanceMember_Kind + "." + CRDGroupVersion.String()
	InstanceMember_GroupVersionKind = CRDGroupVersion.WithKind(InstanceMember_Kind)
)

func init() {
	SchemeBuilder.Register(&InstanceMember{}, &InstanceMemberList{})
}
