/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type OrganizationMetadataInitParameters struct {

	// (String) The key of a metadata entry
	// The key of a metadata entry
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) ID of the organization
	// ID of the organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) The string representation of a metadata entry value. For binary data, use the base64encode function.
	// The string representation of a metadata entry value. For binary data, use the base64encode function.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type OrganizationMetadataObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The key of a metadata entry
	// The key of a metadata entry
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) ID of the organization
	// ID of the organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) The string representation of a metadata entry value. For binary data, use the base64encode function.
	// The string representation of a metadata entry value. For binary data, use the base64encode function.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type OrganizationMetadataParameters struct {

	// (String) The key of a metadata entry
	// The key of a metadata entry
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) ID of the organization
	// ID of the organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) The string representation of a metadata entry value. For binary data, use the base64encode function.
	// The string representation of a metadata entry value. For binary data, use the base64encode function.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// OrganizationMetadataSpec defines the desired state of OrganizationMetadata
type OrganizationMetadataSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OrganizationMetadataParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationMetadataInitParameters `json:"initProvider,omitempty"`
}

// OrganizationMetadataStatus defines the observed state of OrganizationMetadata.
type OrganizationMetadataStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OrganizationMetadataObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationMetadata is the Schema for the OrganizationMetadatas API. Add a custom attribute to the organization like its location or an identifier in another system. You can use this information in your actions.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,zitadel}
type OrganizationMetadata struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.value) || (has(self.initProvider) && has(self.initProvider.value))",message="spec.forProvider.value is a required parameter"
	Spec   OrganizationMetadataSpec   `json:"spec"`
	Status OrganizationMetadataStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationMetadataList contains a list of OrganizationMetadatas
type OrganizationMetadataList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationMetadata `json:"items"`
}

// Repository type metadata.
var (
	OrganizationMetadata_Kind             = "OrganizationMetadata"
	OrganizationMetadata_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationMetadata_Kind}.String()
	OrganizationMetadata_KindAPIVersion   = OrganizationMetadata_Kind + "." + CRDGroupVersion.String()
	OrganizationMetadata_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationMetadata_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationMetadata{}, &OrganizationMetadataList{})
}
