apiVersion: zitadel.crossplane.io/v1alpha1
kind: ApplicationApi
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/applicationapi
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    authMethodType: API_AUTH_METHOD_TYPE_BASIC
    name: applicationapi
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_project
