apiVersion: zitadel.crossplane.io/v1alpha1
kind: ApplicationOidc
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/applicationoidc
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    accessTokenRoleAssertion: false
    accessTokenType: OIDC_TOKEN_TYPE_BEARER
    additionalOrigins: []
    appType: OIDC_APP_TYPE_WEB
    authMethodType: OIDC_AUTH_METHOD_TYPE_BASIC
    clockSkew: 0s
    devMode: true
    grantTypes:
    - OIDC_GRANT_TYPE_AUTHORIZATION_CODE
    idTokenRoleAssertion: false
    idTokenUserinfoAssertion: false
    name: applicationoidc
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    postLogoutRedirectUris:
    - https://localhost.com
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_project
    redirectUris:
    - https://localhost.com
    responseTypes:
    - OIDC_RESPONSE_TYPE_CODE
    skipNativeAppSuccessPage: false
    version: OIDC_VERSION_1_0
