apiVersion: zitadel.crossplane.io/v1alpha1
kind: DefaultPasswordComplexityPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/defaultpasswordcomplexitypolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    hasLowercase: true
    hasNumber: true
    hasSymbol: true
    hasUppercase: true
    minLength: "8"
