apiVersion: zitadel.crossplane.io/v1alpha1
kind: Domain
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/domain
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    isPrimary: false
    name: zitadel.default.127.0.0.1.sslip.io
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
