apiVersion: zitadel.crossplane.io/v1alpha1
kind: IdpAzureAd
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/idpazuread
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    autoLinking: AUTO_LINKING_OPTION_USERNAME
    clientId: 9065bfc8-a08a...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    emailVerified: true
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    name: Azure AD
    scopes:
    - openid
    - profile
    - email
    - User.Read
    tenantType: AZURE_AD_TENANT_TYPE_ORGANISATIONS
