apiVersion: zitadel.crossplane.io/v1alpha1
kind: IdpGoogle
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/idpgoogle
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    autoLinking: AUTO_LINKING_OPTION_USERNAME
    clientId: 182902...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    name: Google
    scopes:
    - openid
    - profile
    - email
