apiVersion: zitadel.crossplane.io/v1alpha1
kind: IdpGitlab
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/idpgitlab
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    autoLinking: AUTO_LINKING_OPTION_USERNAME
    clientId: 15765e...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    name: GitLab
    scopes:
    - openid
    - profile
    - email
