apiVersion: zitadel.crossplane.io/v1alpha1
kind: IdpOidc
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/idpoidc
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    autoLinking: AUTO_LINKING_OPTION_USERNAME
    clientId: a_client_id
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isIdTokenMapping: true
    isLinkingAllowed: false
    issuer: https://example.com
    name: My Generic OIDC IDP
    scopes:
    - openid
    - profile
    - email
