apiVersion: zitadel.crossplane.io/v1alpha1
kind: MachineKey
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/machinekey
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    expirationDate: "2519-04-01T08:45:00Z"
    keyType: KEY_TYPE_JSON
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApj7JHjDLo2TwiJznwMrD
      97ybWoRegSK1rx37+i+Yrmhaee0GuOyj+hWG8/yKazAbZfYB0atO/zHxy1BtFNfX
      uYZS689TvfZVP6TctonH0VTlDDKOjmkGl472DhJvLvwjPXq1e55jS0kToK5lGRW6
      Qrgm7m/KiF96Qmp5kUbF1sThVtKBW9GIAuzWEk3O9opftd/NH3BxvUToWLgG/GFx
      hLeOTrcuPibVHkHbIjt1VHaOD8rKAaRV+KBZUmyS9vdo629wfSx/ylUmwWZ6YUTj
      khnqTi0s7j/oLGJNk+DSjMzkcgls0gzXAwPfiEnjEB+Xxw3LnR6k17HyYxqQs7kz
      ZwIDAQAB
      -----END PUBLIC KEY-----
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_machine_user
