apiVersion: zitadel.crossplane.io/v1alpha1
kind: OrganizationIdpJwt
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/organizationidpjwt
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    autoRegister: false
    headerName: x-auth-token
    issuer: https://google.com
    jwtEndpoint: https://jwtendpoint.com/jwt
    keysEndpoint: https://jwtendpoint.com/keys
    name: jwtidp
    orgId: ${data.zitadel_org.default.id}
    stylingType: STYLING_TYPE_UNSPECIFIED
