apiVersion: zitadel.crossplane.io/v1alpha1
kind: OrganizationIdpLdap
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/organizationidpldap
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    autoLinking: AUTO_LINKING_OPTION_USERNAME
    baseDn: dc=example,dc=com
    bindDn: cn=admin,dc=example,dc=com
    bindPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    firstNameAttribute: firstname
    idAttribute: uid
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    lastNameAttribute: lastname
    name: LDAP
    orgId: ${data.zitadel_org.default.id}
    servers:
    - ldaps://my.primary.server:389
    - ldaps://my.secondary.server:389
    startTls: false
    timeout: 10s
    userBase: dn
    userFilters:
    - uid
    - email
    userObjectClasses:
    - inetOrgPerson
