apiVersion: zitadel.crossplane.io/v1alpha1
kind: OrganizationIdpGithubEs
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/organizationidpgithubes
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    authorizationEndpoint: https://auth.endpoint
    autoLinking: AUTO_LINKING_OPTION_USERNAME
    clientId: 86a165...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    name: GitHub Enterprise Server
    orgId: ${data.zitadel_org.default.id}
    scopes:
    - openid
    - profile
    - email
    tokenEndpoint: https://token.endpoint
    userEndpoint: https://user.endpoint
