apiVersion: zitadel.crossplane.io/v1alpha1
kind: OrganizationIdpOauth
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/organizationidpoauth
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    authorizationEndpoint: https://accounts.google.com/o/oauth2/v2/auth
    autoLinking: AUTO_LINKING_OPTION_USERNAME
    clientId: 15765e...
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    idAttribute: user_id
    isAutoCreation: false
    isAutoUpdate: true
    isCreationAllowed: true
    isLinkingAllowed: false
    name: GitLab
    orgId: ${data.zitadel_org.default.id}
    scopes:
    - openid
    - profile
    - email
    tokenEndpoint: https://oauth2.googleapis.com/token
    userEndpoint: https://openidconnect.googleapis.com/v1/userinfo
