apiVersion: zitadel.crossplane.io/v1alpha1
kind: PasswordComplexityPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/passwordcomplexitypolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    hasLowercase: true
    hasNumber: true
    hasSymbol: true
    hasUppercase: true
    minLength: "8"
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
