apiVersion: zitadel.crossplane.io/v1alpha1
kind: PersonalAccessToken
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/personalaccesstoken
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    expirationDate: "2519-04-01T08:45:00Z"
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_machine_user
