apiVersion: zitadel.crossplane.io/v1alpha1
kind: ProjectGrant
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/projectgrant
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    grantedOrgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_project
    roleKeys:
    - super-user
