apiVersion: zitadel.crossplane.io/v1alpha1
kind: ProjectMember
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/projectmember
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_project
    roles:
    - PROJECT_OWNER
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_human_user
