apiVersion: zitadel.crossplane.io/v1alpha1
kind: ProjectGrantMember
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/projectgrantmember
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    grantId: "123456789012345678"
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_project
    roles:
    - PROJECT_GRANT_OWNER
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_human_user
