apiVersion: zitadel.crossplane.io/v1alpha1
kind: TriggerActions
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/triggeractions
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    actionIds:
    - ${data.zitadel_action.default.id}
    flowType: FLOW_TYPE_CUSTOMISE_TOKEN
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    triggerType: TRIGGER_TYPE_PRE_ACCESS_TOKEN_CREATION
