apiVersion: zitadel.crossplane.io/v1alpha1
kind: UserGrant
metadata:
  annotations:
    meta.upbound.io/example-id: zitadel/v1alpha1/usergrant
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_project
    roleKeys:
    - super-user
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_human_user
