name: Comment Commands

on: issue_comment

jobs:
  comment-commands:
    uses: upbound/official-providers-ci/.github/workflows/provider-commands.yml@cd6215984633723be29e7709f39e3a83aaeb0baf # standard-runners